### ISSUE TITLE
Can we got a permanent static download link for the latest build?

### ISSUE THREAD

**Issue by sjva22306** [Krappa322/arcdps_healing_stats#23]
Is there anyway that you could offer a persistent download link such as the one from arcdps **"https://www.deltaconnected.com/arcdps/x64/d3d9.dll"** that will always have the latest build?

This is make the player's lives easier by making the download process a lot easier.

Currently, going to https://github.com/Krappa322/arcdps_healing_stats/releases/latest shows the 2.4 version, but the 2.5rc2  is actually the latest version.

And attempting to download the file directly using the path fails too: https://github.com/Krappa322/arcdps_healing_stats/releases/download/v2.5rc2/arcdps_healing_stats.dll

Please assist.

Thanks.

**Comment by Krappa322** [comment]
2.5rc2 is a pre-release, which is why it's not shown when looking at latest release. When deemed stable, it will be released and then show up as the latest release :)

You can also control this through the "auto update" option in-game, where you can choose whether you want to automatically download latest stable or latest pre-release

**Comment by sjva22306** [comment]
Where is the auto update option?
I don't see it.


- SJ.

**Comment by Krappa322** [comment]
Sorry, I mixed up my addons. I've yet to make one for this addon

**Comment by Krappa322** [comment]
Auto update is tracked in https://github.com/Krappa322/arcdps_healing_stats/issues/24

Static download link is not something I'm interested in pursuing right now

**Comment by Krappa322** [comment]
Auto updating has been added in the latest pre-release
