### ISSUE TITLE
[Feature Suggestion] Split Heal Table into 3 Separate Windows

### ISSUE THREAD

**Issue by MoXAriApph** [Krappa322/arcdps_healing_stats#3]
Essentially title, it would make more sense than having it in 1 window and having to scroll through all of it or hide stuff in the menu.

**Comment by Krappa322** [comment]
Currently working on basically this :)

Planning to do something similar to arcdps area stats except it shows healing instead

**Comment by Krappa322** [comment]
You can find a pre-release of this now in https://github.com/Krappa322/arcdps_healing_stats/releases/tag/v1.0rc2

Feedback is much appreciated :)

**Comment by MoXAriApph** [comment]
Have been using it all week, no major issues as of yet, everything seems to be working perfectly o7

**Comment by Krappa322** [comment]
Awesome :) If you have any other UI requests, I'm all ears

**Comment by Krappa322** [comment]
Fixed in 747874da678933fd00840acd83bd904c7e8fc05b

**Comment by MoXAriApph** [comment]
> Awesome :) If you have any other UI requests, I'm all ears

Possibly add something to show healing skills leaking to the other subs, 5-target skills like Healing Spring, Well of Blood and Breakrazors bastion can leak over, but it would be beneficial to know how much.

Ex. 
Healing Spring will leak over both normal healing and regen when your sub is on full health
The alternative skill would be Water spirit, which is 10-man
For all intents and purposes, you'd wan Healing Spring on every fight except Cairn if you can properly hit everyone with healing spring
If you can't hit everyone due to movement in fights like Cairn, SH or even something like Matthias, it would be beneficial to know if your overhealing on Healing spring is worse than just using Water Spirit

**Comment by Krappa322** [comment]
So this is sort of possible already, if you press healing spring you get a details window and then you can see targets healed in there. Adding another tab to show Group/Squad/All stats there seems like a good idea

The other part to this is showing overhealing, which is definitely in the plans. I don't get any events or anything for that though so I would have to simulate it myself, which becomes quite complex when considering the fact that I need to know not only the players healing power, but also their food, if they have lingering light skilled, if their weapon has Sigil of Transference, etc. An intermediate step is to calculate how many times skills are cast, because then you can know hits missed, which is useful.
